// restaurante-frontend/src/app/restaurants/restaurants.component.ts
import {Component, OnInit} from '@angular/core';
import {Restaurant} from './shared/restaurant';
import {RestaurantService} from "./shared/restaurant.service";

@Component({
  selector: 'app-restaurants',
  templateUrl: './restaurants.component.html',
})
export class RestaurantsComponent implements OnInit {
  name: String;
  restaurants: Restaurant[] = [];

  constructor(private restaurantService: RestaurantService) {
  }

  ngOnInit() {
    this.restaurantService.getRestaurants().subscribe(data => this.restaurants = data);
  }

  search() {
    this.restaurantService.getRestaurants(this.name).subscribe(data => {
      this.restaurants = data
    });
  }

  delete(restaurant) {
    if (confirm("Você tem certeza? ")) {
      this.restaurants.splice(this.restaurants.indexOf(restaurant), 1);

      this.restaurantService.delete(restaurant.id)
        .subscribe(null);
    }
  }

}

<h2> Restaurantes </h2>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Filtros</h3>
  </div>
  <div class="panel-body">
    <form (ngSubmit)="search()">
      <div class="row">
        <div class="col-lg-6">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Nome" id="name" [(ngModel)]="name" name="name">
            <span class="input-group-btn">
          <button class="btn btn-primary" type="submit">
            <fa [name]="'search'"></fa>
            Pesquisar
           </button>
        </span>
          </div>
        </div>
        <div class="col-lg-6">
          <button class="btn btn-success" routerLink="/restaurant/new">
            <fa [name]="'plus'"></fa>
            Cadastrar novo restaurante
          </button>
        </div>
      </div>

    </form>
  </div>
</div>

<div class="table-container">
  <table class="table table-striped">
    <colgroup>
      <col class="table-icon">
      <col class="table-icon">
      <col>
    </colgroup>
    <thead>
    <tr>
      <th></th>
      <th></th>
      <th data-field="name">Restaurantes</th>
    </tr>
    </thead>

    <tbody>
    <tr *ngFor="let r of restaurants">
      <td class="td-icon td-icon-red">
        <a (click)="delete(r)">
          <fa [name]="'minus'"></fa>
        </a>
      </td>

      <td class="td-icon">
        <a [routerLink]="['/restaurant', r.id]">
          <fa [name]="'edit'"></fa>
        </a>
      </td>
      <td>{{ r.name }}</td>
    </tr>
    </tbody>
  </table>
</div>

// restaurante-frontend-react/src/restaurants/restaurants.js
import React, {Fragment} from 'react';
import {Link} from 'react-router-dom';
import {connect} from "react-redux";

class Restaurants extends React.Component {
    componentDidMount() {
        this.props.listRestaurants();
    }
    
    render() {
        return (
            <Fragment>
                <h2> Restaurantes </h2>

                <div className="panel panel-default">
                    <div className="panel-heading">
                        <h3 className="panel-title">Filtros</h3>
                    </div>
                    <div className="panel-body">
                        <form>
                            <div className="row">
                                <div className="col-lg-6">
                                    <div className="input-group">
                                        <input type="text" className="form-control" placeholder="Nome"
                                               id="name" name=" name"/>
                                        <span className=" input-group-btn">
                                    <button className=" btn btn-primary" type="submit">
                                        <i className="fa fa-search"/>
                                     </button>
                                </span>
                                    </div>
                                </div>
                                <div className="col-lg-6">
                                    <Link to="/restaurant" className="btn btn-success">
                                        <i className="fa fa-plus"/>
                                        Cadastrar novo restaurante
                                    </Link>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <div className="table-container">
                    <table className="table table-striped">
                        <colgroup>
                            <col className="table-icon"/>
                            <col className="table-icon"/>
                            <col/>
                        </colgroup>
                        <thead>
                        <tr>
                            <th/>
                            <th/>
                            <th data-field="name">Restaurantes</th>
                        </tr>
                        </thead>

                        <tbody>
                        <tr>
                            <td className=" td-icon td-icon-red">
                                <a>
                                    <i className="fa fa-minus"/>
                                </a>
                            </td>

                            <td className="td-icon">
                                <Link to="/restaurant">
                                    <i className="fa fa-edit"/>
                                </Link>
                            </td>
                            <td> Name</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </Fragment>
        );
    }
}


const mapStateToProps = state => {
    return {
        restaurants: state.restaurants
    }
};

const mapDispatchToProps = dispatch => {
    return {
        listRestaurants: () => dispatch({type: 'LIST_RESTAURANTS'})
    }
};

export default connect(
    mapStateToProps,
    mapDispatchToProps
)(Restaurants);
