// restaurante-frontend/src/app/meals/meals.component.ts
import {Component, OnInit} from '@angular/core';
import {MealService} from "./shared/meal.service";
import {Meal} from "./shared/meal";

@Component({
  selector: 'app-meals',
  templateUrl: './meals.component.html',
})
export class MealsComponent implements OnInit {

  meals: Meal[] = [];
  name: String;

  constructor(private mealService: MealService) {
  }

  ngOnInit() {
    this.mealService.getMeals().subscribe(data => this.meals = data);
  }

  search() {
    this.mealService.getMeals(this.name).subscribe(data => {this.meals = data});
  }

  delete(meal) {
    if (confirm("Você tem certeza? ")) {
      this.meals.splice(this.meals.indexOf(meal), 1);

      this.mealService.delete(meal.id)
        .subscribe(null);
    }
  }

}

<h2> Pratos </h2>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Filtros</h3>
  </div>
  <div class="panel-body">
    <form (ngSubmit)="search()">
      <div class="row">
        <div class="col-lg-6">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Nome" id="name" [(ngModel)]="name" name="name">
            <span class="input-group-btn">
          <button class="btn btn-primary" type="submit">
            <fa [name]="'search'"></fa>
            Pesquisar
           </button>
        </span>
          </div>
        </div>
        <div class="col-lg-6">
          <button class="btn btn-success" routerLink="/meal/new">
            <fa [name]="'plus'"></fa>
            Cadastrar novo prato
          </button>
        </div>
      </div>
    </form>
  </div>
</div>

<div class="table-container">
  <table class="table table-striped">
    <colgroup>
      <col class="table-icon">
      <col class="table-icon">
      <col>
      <col>
      <col>
    </colgroup>
    <thead>
    <tr>
      <th></th>
      <th></th>
      <th>Restaurante</th>
      <th>Prato</th>
      <th>Preço</th>
    </tr>
    </thead>

    <tbody>
    <tr *ngFor="let m of meals">
      <td class="td-icon td-icon-red">
        <a (click)="delete(m)">
          <fa [name]="'minus'"></fa>
        </a>
      </td>

      <td class="td-icon">
        <a [routerLink]="['/meal', m.id]">
          <fa [name]="'edit'"></fa>
        </a>
      </td>

      <td class="table-border">{{ m.restaurant.name }}</td>
      <td class="table-border">{{ m.name }}</td>
      <td>{{ m.price }}</td>
    </tr>
    </tbody>
  </table>
</div>

// restaurante-frontend-react/src/meals/meals.js
import React, {Fragment} from 'react';
import {Link} from 'react-router-dom';

const Meals = () =>
    <Fragment>
        <h2> Pratos </h2>

        <div className="panel panel-default">
            <div className="panel-heading">
                <h3 className="panel-title">Filtros</h3>
            </div>
            <div className="panel-body">
                <form>
                    <div className="row">
                        <div className="col-lg-6">
                            <div className="input-group">
                                <input type="text" className="form-control" placeholder="Nome"
                                       id="name" name=" name"/>
                                <span className="input-group-btn">
                                    <button className="btn btn-primary" type="submit">
                                        <i className="fa fa-search"/>
                                     </button>
                                </span>
                            </div>
                        </div>
                        <div className="col-lg-6">
                            <Link to="/meal" className="btn btn-success">
                                <i className="fa fa-plus"/>
                                Cadastrar novo prato
                            </Link>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div className="table-container">
            <table className="table table-striped">
                <colgroup>
                    <col className="table-icon"/>
                    <col className="table-icon"/>
                    <col/>
                    <col/>
                    <col/>
                </colgroup>
                <thead>
                <tr>
                    <th/>
                    <th/>
                    <th>Restaurante</th>
                    <th>Prato</th>
                    <th>Preço</th>
                </tr>
                </thead>

                <tbody>
                <tr>
                    <td className="td-icon td-icon-red">
                        <a>
                            <i className="fa fa-minus"/>
                        </a>
                    </td>

                    <td className="td-icon">
                        <Link to="/meal">
                            <i className="fa fa-edit"/>
                        </Link>
                    </td>
                    <td> Restaurante</td>
                    <td> Name</td>
                    <td> Preço</td>
                </tr>
                </tbody>
            </table>
        </div>
    </Fragment>

export default Meals;
